name: Android Build

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: app/build/outputs/apk/release/app-release.apk
